# Generated by Django 4.2 on 2023-04-29 05:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_time_of_adminstration_dose_time_of_administration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
            preserve_default=False,
        ),
    ]
